---
# roles/vault_tls_auth/tasks/main.yml
# Download Vault CA certificate from Vault server
# - name: Download Vault CA certificate
#   ansible.builtin.get_url:
#     url: "{{ vault_addr }}/v1/pki/ca/pem"
#     dest: /etc/pki/ca-trust/source/anchors/vault-ca.crt
#     mode: '0644'
#     force: true
#     validate_certs: false  # Only for initial CA download
#   register: ca_download
# # Update CA trust store after download
# - name: Update CA trust store
#   ansible.builtin.command:
#     cmd: update-ca-trust
#   when: ca_download.changed

# Ensure Vault CA certificate is installed
- name: Check if Vault CA certificate exists
  ansible.builtin.stat:
    path: /etc/pki/ca-trust/source/anchors/vault-ca.crt
  register: ca_stat

- name: Fail if Vault CA certificate is missing
  ansible.builtin.fail:
    msg: "Vault CA certificate not found in /etc/pki/ca-trust/source/anchors"
  when: not ca_stat.stat.exists

# Debug: Echo the Vault CA certificate content to verify it
- name: Display the Vault CA certificate content
  ansible.builtin.command:
    cmd: cat /etc/pki/ca-trust/source/anchors/vault-ca.crt
  register: vault_ca_content
  changed_when: false
  failed_when: false

- name: Show Vault CA certificate content
  debug:
    msg: "Vault CA certificate content: {{ vault_ca_content.stdout }}"

# Verify if the certificate is valid with OpenSSL
- name: Verify Vault CA certificate with OpenSSL
  ansible.builtin.command:
    cmd: openssl x509 -in /etc/pki/ca-trust/source/anchors/vault-ca.crt -text -noout
  register: openssl_cert_verify
  changed_when: false
  failed_when: false

- name: Show OpenSSL certificate verification result
  debug:
    msg: "OpenSSL certificate verification result: {{ openssl_cert_verify.stdout }}"

# Install Python3 and pip if not present
- name: Install Python3 and pip
  ansible.builtin.package:
    name: 
      - python3
      - python3-pip
    state: present
  become: true

# Install pip-system-certs to resolve SSL certificate issues
- name: Install pip-system-certs
  ansible.builtin.pip:
    name: pip-system-certs
    executable: pip3
  become: true

# Debug: Check certificate trust
- name: Check if the Vault CA is in the trust store
  ansible.builtin.command: update-ca-trust list
  register: ca_trust_check
  changed_when: false
  failed_when: false

- name: Display Vault CA trust status
  debug:
    msg: "Vault CA trust store: {{ ca_trust_check.stdout }}"

# Check and install hvac Python library
- name: Check if hvac Python library is installed
  ansible.builtin.command:
    cmd: "/usr/bin/python3 -c 'import hvac'"
  register: hvac_check
  ignore_errors: true
  changed_when: false

- name: Install hvac Python library if not present
  ansible.builtin.pip:
    name: hvac
    executable: pip3
    state: present
  become: true
  when: hvac_check.rc != 0

- name: Verify hvac installation
  ansible.builtin.command:
    cmd: "/usr/bin/python3 -c 'import hvac'"
  register: hvac_verify
  failed_when: hvac_verify.rc != 0
  changed_when: false

- name: Fail if hvac library installation failed
  ansible.builtin.fail:
    msg: "Failed to install hvac library in the Execution Environment."
  when: hvac_verify.rc != 0

# Update the SSL environment variables task
- name: Set SSL environment variables
  ansible.builtin.set_fact:
    vault_ssl_env:
      VAULT_CACERT: "/etc/pki/ca-trust/source/anchors/vault-ca.crt"
      REQUESTS_CA_BUNDLE: "/etc/pki/ca-trust/source/anchors/vault-ca.crt"
      SSL_CERT_FILE: "/etc/pki/ca-trust/source/anchors/vault-ca.crt"
      PYTHONHTTPSVERIFY: "1"

# Test Vault connectivity
- name: Test Vault connectivity
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/sys/health"
    method: GET
    return_content: true
    validate_certs: true
    ca_path: "/etc/pki/ca-trust/source/anchors/vault-ca.crt"
    status_code: [200, 429, 472, 473, 501, 503]
    headers:
      Content-Type: "application/json"
  environment: "{{ vault_ssl_env }}"
  register: vault_health
  retries: 4
  delay: 5
  timeout: 10
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Debug response from Vault connectivity test
  debug:
    var: vault_health

# Ensure VAULT_ADDR environment variable is set
- name: Ensure VAULT_ADDR environment variable is set
  ansible.builtin.assert:
    that:
      - vault_addr is defined
      - vault_addr | length > 0
    fail_msg: "VAULT_ADDR is not set or is empty!"

# Ensure Vault authentication credentials are defined
- name: Ensure Vault authentication credentials are defined
  ansible.builtin.assert:
    that:
      - role_id is defined
      - role_id | length > 0
      - secret_id is defined
      - secret_id | length > 0
    fail_msg: "Vault AppRole authentication credentials (role_id or secret_id) are not set!"

# Update the certificate generation task
- name: Issue certificate from Vault PKI
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_addr }}"
    role_name: "{{ vault_pki_role }}"
    engine_mount_point: "{{ vault_pki_path }}"
    common_name: "{{ inventory_hostname }}.{{ domain }}"
    auth_method: approle
    role_id: "{{ role_id }}"
    secret_id: "{{ secret_id }}"
    validate_certs: true
    ca_cert: "/etc/pki/ca-trust/source/anchors/vault-ca.crt"
    ttl: "{{ vault_cert_ttl | default('8760h') }}"
  environment: "{{ vault_ssl_env }}"
  register: vault_cert_response
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Display wrapped token
  debug:
    msg: "Wrapped Token: {{ vault_cert_response.wrap_info.token }}"

- name: Store wrapped response in variable
  set_fact:
    wrapped_cert:
      token: "{{ vault_cert_response.wrap_info.token }}"
      ttl: "{{ vault_cert_response.wrap_info.ttl }}"
      creation_time: "{{ vault_cert_response.wrap_info.creation_time }}"

# Copy the wrapped certificate to the target machine
- name: Copy wrapped response to the target machine
  ansible.builtin.copy:
    content: "{{ vault_cert_response.wrap_info.token }}"
    dest: "/etc/vault.d/wrapped_token"
    mode: "0644"
  delegate_to: "{{ target_hostname }}"
  become: true

- name: Unwrap token and get certificate data
  community.hashi_vault.vault_write:
    path: sys/wrapping/unwrap
    token: "{{ vault_cert_response.wrap_info.token }}"
  register: unwrapped_cert
  delegate_to: "{{ target_hostname }}"

- name: Write certificate files
  copy:
    content: "{{ item.content }}"
    dest: "{{ cert_dir | default('/etc/ssl/private') }}/{{ item.filename }}"
    mode: "{{ item.mode }}"
  loop:
    - { content: "{{ unwrapped_cert.data.data.certificate }}", filename: "cert.pem", mode: "0644" }
    - { content: "{{ unwrapped_cert.data.data.private_key }}", filename: "key.pem", mode: "0600" }
    - { content: "{{ unwrapped_cert.data.data.issuing_ca }}", filename: "ca.pem", mode: "0644" }
  no_log: true  # Hide sensitive content from logs
  delegate_to: "{{ target_hostname }}"

- name: Create template directory for certificate renewal
  file:
    path: "{{ cert_dir }}/templates"
    state: directory
    mode: '0750'
  delegate_to: "{{ target_hostname }}"

- name: Deploy certificate renewal template
  template:
    src: cert-renewal.ctmpl.j2
    dest: "{{ cert_dir }}/templates/cert-renewal.ctmpl"
    mode: '0640'
  delegate_to: "{{ target_hostname }}"

# Need to clobber the existing Vault Agent Configuration to use new TLS Auth
- name: Deploy Vault Agent configuration
  template:
    src: "vault-agent-tls-config.hcl.j2"
    dest: "{{ vault_agent_config_file }}"
    force: true
  notify:
    - restart vault-agent
  delegate_to: "{{ target_hostname }}"
