---
# TPM Task Switcher
# This file determines which TPM approach to use based on variables

- name: Use simplified key generation (recommended for demo)
  ansible.builtin.include_tasks: main-simplified.yml
  when: vault_tpm_simplified | default(true)

- name: Use full TPM integration
  ansible.builtin.include_tasks: main-full-tpm.yml
  when: not (vault_tpm_simplified | default(true))
